### ISSUE TITLE
Add * and _ to surround chars list (for markdown)

### ISSUE THREAD

**Issue by maximbaz** [alexherbo2/auto-pairs.kak#10]
Would be cool to select a phrase and make it italic or bold using surround feature.

**Comment by alexherbo2** [comment]
``` kak
hook global WinSetOption filetype=markdown %{
  set-option -add buffer auto_pairs_surround _ _ * *
}
```

**Comment by maximbaz** [comment]
This will overwrite the default list, right? Can I append instead?

**Comment by maximbaz** [comment]
I see, that was a good decision to split two lists. Should we include underscore and star in the default config of surround option, and if not, why not? 😋

**Comment by alexherbo2** [comment]
@maximbaz I reverted the change.

**Comment by alexherbo2** [comment]
Is the current state satisfying?

**Comment by maximbaz** [comment]
I tested both approaches, everything is just perfect 👍
