### ISSUE TITLE
Delete surrounding brackets doesn't work when spaces are involved

### ISSUE THREAD

**Issue by maximbaz** [alexherbo2/auto-pairs.kak#13]
```
[ cmd ] && echo yes
```

Select `cmd`, type `:auto-pairs-surround`, press <kbd>Backspace</kbd> twice.

Expected:

```
cmd && echo yes
```

Actual:

```
error running hook InsertDelete([)/auto-pairs-surround-delete: 1:1: 'auto-pairs-surround-delete-opener' 2:4: 'execute-keys' no selections remaining
```

**Comment by andreyorst** [comment]
It would be also awesome to have ability to surround selection with spaces while we inside of all kind of braces. This is opposite behavior from this issue, but it compliments it

**Comment by maximbaz** [comment]
Good point, extracted in #15

**Comment by alexherbo2** [comment]
@andreyorst I added this support along with the fix.
