### ISSUE TITLE
regression: `o` selects previous line

### ISSUE THREAD

**Issue by maximbaz** [alexherbo2/auto-pairs.kak#17]
Paste this:

```
'aaa'
'bbb'
```

Put cursor on the line `'aaa'`.
Press `o`.
The line `'aaa'` is selected, but shouldn't.

**Comment by alexherbo2** [comment]
I can’t reproduce.

**Comment by andreyorst** [comment]
I can reproduce it too. It doesn't happen on non-quoted lines.

![o](https://user-images.githubusercontent.com/19470159/47492025-c3491800-d854-11e8-8f08-0c4045a800a4.gif)

**Comment by andreyorst** [comment]
Thanks!
