### ISSUE TITLE
Pressing `o` behaves incorrectly

### ISSUE THREAD

**Issue by evanrelf** [alexherbo2/auto-pairs.kak#19]
Pressing <kbd>o</kbd> does create a new line below the current line, however the cursor does not go to that line. Instead, the current line is selected and the cursor is left at the end.

Unfortunately, the test added [in this commit](https://github.com/alexherbo2/auto-pairs.kak/commit/50901ab10827a5e2555dfcbd4ab8b3309b7ba203) doesn't detect this behavior because it's only checking the contents of the buffer, not the state of the cursor or selection.

**Comment by maximbaz** [comment]
Also see this bug I created earlier, just for reference: https://github.com/mawww/kakoune/issues/2532

**Comment by evanrelf** [comment]
The GIF in mawww/kakoune#2532 represents what I'm experiencing exactly.

- Version: `Kakoune v2018.09.04`
- Contents of `kakrc`:

```
source ~/.config/kak/plugins/plug.kak/rc/plug.kak
plug 'andreyorst/plug.kak' 'noload'
plug 'alexherbo2/auto-pairs.kak' %{
  hook global WinCreate .* %{ auto-pairs-enable }
}
```

---

Steps to reproduce:

Using the configuration from above:

1. Open Kakoune (no file necessary)
2. Type something on the first line (e.g. "hello world")
3. Press <kbd>o</kbd>
4. A new line is created below "hello world", and "hello world" becomes selected

**Comment by maximbaz** [comment]
Can you ensure that you truly run latest auto-pairs and plug didn't cache some old version?

**Comment by evanrelf** [comment]
Yes, I just reinstalled plug and auto-pairs. I'm on commit `50901ab` ("Add test for `o`") and it still happens.

**Comment by maximbaz** [comment]
One more test please 😉 

```
{
}
```

Cursor is on the closing bracket, press `O<Backspace>`, what do you get?

**Comment by evanrelf** [comment]
If that's a capital `O`, I get this:
```
{

}
```

And my cursor ends up on the top bracket.

---

Also, it seems auto-pairs is treating newlines like pairs: when I press <kbd>Enter</kbd>, newlines are created above and below my cursor. <kbd>Backspace</kbd> deletes them in pairs as well.

I'm very new to Kakoune (longtime Vim user) so please let me know if I'm doing something wrong. But that's literally all I have in my config, and I've freshly installed everything (including Kakoune, from Homebrew)...

**Comment by maximbaz** [comment]
This was the test that was [actually failing](https://travis-ci.org/alexherbo2/auto-pairs.kak/builds/447125918) until `Use printf instead of echo` commit fixed it and `o` (this was visible in the repo earlier today, but @alexherbo2 reshuffled commits and the order in git history is wrong now).

This leads me to believe that somehow you are indeed using an old version of auto-pairs. Try not using plug, but cloning this repo and sourcing auto-pairs.kak directly.

**Comment by evanrelf** [comment]
I checked with `git log` and I was on the latest commit when installing with plug.

Just downloaded [`auto-pairs.kak`](https://raw.githubusercontent.com/alexherbo2/auto-pairs.kak/master/rc/auto-pairs.kak) from `master` manually using `curl`, and sourced the file manually instead of using plug.

Still have the same problem 😕

**Comment by maximbaz** [comment]
What's your OS and to which shell does the `/bin/sh` link to?

As you can see, we finally have unit-tests running and green, which means that the latest master of auto-pairs was tested against the latest master of kakoune and all tests (including the one called `delete-new-line` (the one about `O<Backspace>`)) is passing on Ubuntu machine with `/bin/sh` as POSIX-compatible `dash`. It also works on my laptop, and I was the original reporter of the `o` issue 😄

**Comment by evanrelf** [comment]
- macOS Mojave 10.14
- I use Fish shell (`fish, version 2.7.1`), but I changed my shell back to the default Bash to test (used `chsh -s /bin/bash`) and the issue still persists when my login shell is Bash (`GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin18.0.0)`)

**Comment by maximbaz** [comment]
Login shell doesn't matter, what matters is which shell is behind the `/bin/sh` symlink — if it is non-POSIX compliant shell (like `fish`), you'll get all sorts of troubles. I doubt you have this setup, but better double check.

For me `/bin/sh` -> `/usr/bin/sh` -> `/usr/bin/dash`, so auto-pairs uses `dash` even though my login shell is `zsh`.

**Comment by evanrelf** [comment]
`/bin/sh` isn't a symlink according to `readlink`, but running `sh --version` tells me it's Bash:

`GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)`

**Comment by maximbaz** [comment]
I just pushed a change that [made Travis run all tests on both macOS and Ubuntu](https://travis-ci.org/alexherbo2/auto-pairs.kak/builds/447275698). 

@alexherbo2 it's your lucky day, apparently the fix only works on Linux, but not on macOS 😉

**Comment by maximbaz** [comment]
Thanks for doing the tests with me @evanrelf, by the way 😉

**Comment by evanrelf** [comment]
Thanks for your time, @maximbaz! 😊Maybe the issue should be renamed to something about not working on macOS?

**Comment by alexherbo2** [comment]
@evanrelf Can I SSH somewhere so I can try to debug?

**Comment by evanrelf** [comment]
Unfortunately it doesn’t look like there are many services that offer macOS in the cloud. I found this one https://cloudxmac.com but it’s $22/mo.

I might be able to work with you to fix this, since I made the issue and I use a Mac, but I’m not super experienced as a developer or with Kakoune 😅

**Comment by maximbaz** [comment]
Just a quick test, @evanrelf what does this output for you in bash?

```
echo "aaa\nbbb" | paste -s -d'|'
```

**Comment by evanrelf** [comment]
😆
```bash
usage: paste [-s] [-d delimiters] file ...
```

I also tried the following:
```bash
bash-4.4$ paste -s -d '|' <(echo "aaa\nbbb")
aaa\nbbb
```

echo isn't converting the `\n` to a newline, and the man page doesn't list the `-e` flag, only `-n`...

It seems to work with `printf` though:

```bash
bash-4.4$ paste -s -d '|' <(printf "aaa\nbbb")
aaa|bbbbash-4.4$
```

**Comment by maximbaz** [comment]
That's exactly the issue, `printf "aaa\nbbb" | paste -s -d'|'` works well on Linux but not on macOS.

@evanrelf how about this command? Notice the last symbol.

```
printf "aaa\nbbb" | paste -s -d '|' -
```

**Comment by evanrelf** [comment]
That works:

```bash
bash-4.4$ printf "aaa\nbbb" | paste -s -d '|' -
aaa|bbbbash-4.4$
```

**Comment by maximbaz** [comment]
Cool, try the latest `master` please 😉  
I also scheduled a Travis run: https://travis-ci.org/alexherbo2/auto-pairs.kak/builds/447457730
