### ISSUE TITLE
Doesn't work in mac

### ISSUE THREAD

**Issue by vbauerster** [alexherbo2/auto-pairs.kak#2]
After entering `:auto-pairs-enable` command, I expect auto pair completion, but nothing happens.
For example I enter `{` and result is the same.
I'm using mac os kakoune version.

**Comment by vbauerster** [comment]
Looks like it's not mac specific. I've tried in manjaro linux, and it does not work either.

**Comment by gspia** [comment]
Tried with nixos (from unstable 2018-02 -version), didn't work (so that it would automatically close pairs).
Tried also with kak -n  and sourced auto-pairs.kak separately and it didn't work. 
In all trials the auto-pairs-surround -command works and inserts the closing character.

**Comment by topisani** [comment]
```kak
define-command -hidden -params 2 auto-pairs-insert-opener %{ try %{
  execute-keys -draft ";<a-K>\w<ret>"
  %sh{
    if [[ "$1" == "$2" ]]; then
      echo try %[
      echo   execute-keys -draft '";<a-k>\Q%arg{2}<ret>d"'
      echo ] catch %[
      echo   execute-keys -no-hooks '"%arg{2}<a-;>h"'
      echo ]
    else
      echo execute-keys -no-hooks '"%arg{2}<a-;>h"'
    fi
  }
}}
```
That works for me

**Comment by maximbaz** [comment]
@alexherbo2 just in case you haven't seen this yet, with your commit there's now a weird selection in the end, it doesn't happen with code in #3:

![auto-pairs](https://user-images.githubusercontent.com/1177900/42307229-054ea876-8032-11e8-92f8-050e4d2f2932.gif)

**Comment by alexherbo2** [comment]
I’ve seen it, but I have not the time to investigate into it yet.

**Comment by alexherbo2** [comment]
@maximbaz Do you mind bisect to extract the relevant part?
