### ISSUE TITLE
Right way to override auto_pairs option?

### ISSUE THREAD

**Issue by vbauerster** [alexherbo2/auto-pairs.kak#24]
What is the right way to override global `auto_pairs` option for specific file type?
For example, I've tried following in order to remove `<>` pair:
```
hook global WinSetOption "filetype=go" %{
    set window auto_pairs '(' ')' '{' '}' '[' ']' '"' '"' '''' '''' '`' '`'
}
```
Echoing, shows that there is no `<>` pair, but `<` keeps auto paired with `>`.

**Comment by alexherbo2** [comment]
I need to add a hook on `auto_pairs` option.

Thanks for the catch.
