### ISSUE TITLE
Certain registers assigned to macros failing to play

### ISSUE THREAD

**Issue by nonumeros** [alexherbo2/auto-pairs.kak#25]
Please see https://github.com/mawww/kakoune/issues/2728

In this case by playing a macro with say an assigned register `l` does no longer play that macro after a number of attempts. 

I'm trying to eliminate a few possibilities with this issue in my end. 

So far by commenting out 

     hook global WinCreate .* %{
	     auto-pairs-enable
	    }

it the config file, that specific register seems to replay accordingly.

**Comment by nonumeros** [comment]
It seems as if https://github.com/alexherbo2/auto-pairs.kak/commit/040fca50e0dd5a41e0ef8d1fcfec4403257e83b6 introduced the issue 

Any prior commit seemed to have been working fine

**Comment by Delapouite** [comment]
In the commit above, the `L` register is explicitly set:
```
set-register L %sh(echo ${#2})
```

**Comment by nonumeros** [comment]
@Delapouite yes yes I noticed it

**Comment by nonumeros** [comment]
@Delapouite I haven't followed the plugin since its inception, and if that was the intent by changing the code around, so be it I guess, but it's nonetheless limiting the alphabetic macro options provided by kakoune. 
What next? When is it going to stop? Will Another definition be provided that uses another alphabetic character?

**Comment by nonumeros** [comment]
I'm closing the issue, since it works as designed for the plugin. Not so for the editor.
