### ISSUE TITLE
auto-pairs-surround documentation

### ISSUE THREAD

**Issue by CBenoit** [alexherbo2/auto-pairs.kak#27]
Hi,

This is in the README:
```
map global user S -docstring 'Surround++' ': auto-pairs-surround _ _ * *<ret>'
```
What is the meaning of auto-pairs-surround parameters? There is no documentation for it.
An explanation for this should at least be added in the README.

**Comment by alexherbo2** [comment]
It’s for adding extra pairs.

With this pair, you can for example surround Markdown `**foo**` or `_bar_`.  It’s not a pair you always want though, hence the extra parameters to the command.

**Comment by CBenoit** [comment]
Thank you! May I open a pull request to add this in the readme?

**Comment by alexherbo2** [comment]
Yep
