### ISSUE TITLE
Using words as autopairs

### ISSUE THREAD

**Issue by asyncial** [alexherbo2/auto-pairs.kak#30]
Hey,
is it possible to use full strings as autopairs? For example `if` and `fi` in shellscripts.
Thanks for providing this useful plug in!

**Comment by alexherbo2** [comment]
Not at the moment, but patches are welcome.

I have to check the code, but if my memory is good, it could be done by iterating the pairs, testing `count` <kbd>H</kbd>, where `count` represents the length of the opening pair being iterated, for each selection matching, insert the corresponding closing pair.

**Comment by asyncial** [comment]
Alright, thanks, I will look into it.

**Comment by dgmulf** [comment]
That would be a great feature. :)
