### ISSUE TITLE
lots of space in matching pairs

### ISSUE THREAD

**Issue by BrianHicks** [alexherbo2/auto-pairs.kak#33]
When I type `[ `, I expect to see

```
[ | ]
```

but lately I've been getting

```
[ |        ]
```

(where `|` is the cursor. Apologies for the block formatting, backtick formatting erases the precise amount of spaces!)

This *seems* like something that could be auto-pairs, but I'm not 100% sure. Does this seem likely to you? What other info could I provide you to check? I'm running auto-pairs.kak at 3e529e8002fe07e952c3a895f50dc749eb2b40de

**Comment by alexherbo2** [comment]
I cannot reproduce.  Which version of Kakoune do you have?

Try with:

``` sh
kak -n -e 'source auto-pairs.kak'
```

**Comment by BrianHicks** [comment]
Hmm, I'm really not sure. It seems to go in and out sporadically and I cannot reproduce with the config you sent. 🤷‍♂ 

Perhaps I should close this for now until I have a better way to reproduce.
