### ISSUE TITLE
Exception per file type?

### ISSUE THREAD

**Issue by vbauerster** [alexherbo2/auto-pairs.kak#34]
Is it possible to introduce some exception rule per file type?
For example in rust it's pretty common to type `<'a>`, so when I type `<'` I get `<''` instead.
So I'd like to have exception like do not auto-pair a single quote if previous char is `<`.

**Comment by DERPSQUID9** [comment]
@vbauerster

Try this:

    hook WinSetOption filetype=(<put filetypes here>) %{
        set-option window auto_pairs <put desired pair characters here as individual strings>
    }

For the example you gave with Rust (assuming that you only want to exclude apostrophes and retain everything else), that would be:

    hook WinSetOption filetype=rust %{
        set-option window auto_pairs "(" ")" "{" "}" "[" "]" '"' '"' "`" "`" "“" "”" "‘" "’" "«" "»" "‹" "›"
    }
