### ISSUE TITLE
Auto-pairs adding extra pair when pasting text

### ISSUE THREAD

**Issue by Afonsocraposo** [alexherbo2/auto-pairs.kak#36]
I noticed that when pasting text in insert mode, the plugin adds an extra "pair" at the end.
For example, if in insert mode I paste the following:
```
{

}
```
I get:
```
{

}

}
```
Is there anyway to disable this while pasting text?
Thank you for your help!

**Comment by alexherbo2** [comment]
```
\i<s-insert>
```

**Comment by Afonsocraposo** [comment]
Thank you for your answer! I'm new to Kakoune. Could you please give me more details?

**Comment by alexherbo2** [comment]
<kbd>\\</kbd> disables hooks for the next command, which is <kbd>i</kbd> in that case, so for the whole insert session.

**Comment by Afonsocraposo** [comment]
Thank you so much for your help!
