### ISSUE TITLE
Bad indent after inserting new line between brackets

### ISSUE THREAD

**Issue by CharlesGueunet** [alexherbo2/auto-pairs.kak#39]
Thank for this nice plugin.

Recently, I have observed an annoying behavior when inserting a new line between some separators on my cpp file.
The cursor is | in the following.
```
  {|}
```
press **Enter**:
```
  {
     |
     }
```
I would expect the lower bracket to be aligned with the upper one.
This bug seems to depends on the current filetype. It does not occurs on the `kakrc` but does occur on `cpp` files.

Setup:

* Kakoune on [current master](https://github.com/mawww/kakoune/commit/60dda1a5975338c59298811f22651532a22348f3)
* A kakrc with only prelude and auto-pairs plugins loaded and nothing else.

**Comment by alexherbo2** [comment]
What does happen when you do <kbd>Return</kbd>—<kbd>Escape</kbd>—<kbd>O</kbd> without the plugin?

**Comment by CharlesGueunet** [comment]
In this situation:
```
   {|}
```
pressing return leads to:
```
   {
   |}
```
which makes some sens but using vim lead to the more intuitive result:
```
   {
      |
   }
```

This also means auto-pairs is not the main responsible of this behavior.
I think I will rather continue this discussion on the kakoune discourse then :)
Thank you very much for your help!

**Comment by alexherbo2** [comment]
@CharlesGueunet Without auto-pairs, I have this:

``` cpp
int main() {
  ▌}
```

**Comment by CharlesGueunet** [comment]
@alexherbo2 FYI, I found an older Kakoune on my setup an I had the "intuitive" behavior described in my first post. This is not due to Kakoune itself as the editor has the exact same behavior without any plugins. However, I was on the commit 3e529e8002fe07e952c3a895f50dc749eb2b40de of auto-pairs, before the prelude requirement. This version had the intuitive "behavior". Do you know why this behavior changed ?

**Comment by alexherbo2** [comment]
I was handling the indent in auto-pairs itself.

**Comment by CharlesGueunet** [comment]
If you think the indent is out of scope for this plugin, simply close this PR :)

**Comment by alexherbo2** [comment]
It is hard, because all [filetypes] are wrong.  I feel like if I fix it in auto-pairs, upstream will never get fixed.

[Filetypes]: https://github.com/mawww/kakoune/blob/master/rc/filetype

We just need the filetypes to pass from:

``` cpp
int main() {
  ▌}
```

To:

``` cpp
int main() {
▌}
```

Then auto-pairs can do what we would do interactively: <kbd>Return</kbd>—<kbd>Escape</kbd>—<kbd>O</kbd>.

**Comment by alexherbo2** [comment]
@CharlesGueunet If you feel courageous, fix all `<language>-new-line-inserted` commands in [filetypes]. 😂

[Filetypes]: https://github.com/mawww/kakoune/blob/master/rc/filetype

**Comment by CharlesGueunet** [comment]
I won't say I will fix all of them but I may give a try to fix some for the languages I am familiar with :)

**Comment by maximbaz** [comment]
Could you please explain again where is the problem in filetypes? If in vanilla kak I press this I will get the desired behavior: 

`int main() {<Return>}<Esc>O`

**Comment by CharlesGueunet** [comment]
@maximbaz this sequence work indeed, but my problem is the way Kakoune handles a new line when the cursor is already in between the braces:
```C
int main(){|}
```
In your example, you enter the closing brace by hand.

**Comment by alexherbo2** [comment]
@maximbaz Try this:

```
iint main() {}<left><ret><esc>O
```

**Comment by maximbaz** [comment]
Ah okay, gotcha. What about an alternative scenario then, when you press `int main() {<Return>`, you get to this:

```
int main() {
    ▌
    }
```

Can we make auto-pairs put closing `}` to the correct indentation, as if we were pressing `int main() {<ret>}<esc>O` instead of `int main() {}<left><ret><esc>O`?

**Comment by alexherbo2** [comment]
It is odd.  The closing pair is already inserted when pressing <kbd>Return</kbd> in-between pair.  You want to delete the right and retype it?

**Comment by maximbaz** [comment]
Ooooh, riiiiight, of course, now I get it.... Sorry, totally makes sense now 😄 Now I finally see the full picture 👍 
Then I guess this can be closed, if the fix needs to be done in kakoune?

**Comment by alexherbo2** [comment]
I do not feel courageous 😭 to fix all `<language>-new-line-inserted` commands to take into account <kbd>Return</kbd> can be pressed in the middle of lines.

**Comment by alexherbo2** [comment]
@CharlesGueunet If you use [manual-indent.kak], you can be not affected by that.

[manual-indent.kak]: https://github.com/alexherbo2/manual-indent.kak

**Comment by CharlesGueunet** [comment]
The issue has been fixed in Kakoune thanks to an amazing work:
see [!3620](https://github.com/mawww/kakoune/pull/3620)
