### ISSUE TITLE
Bug with current kakoune master ?

### ISSUE THREAD

**Issue by CharlesGueunet** [alexherbo2/auto-pairs.kak#43]
Hello.

On Kakoune current master ([cfbff4e1](https://github.com/mawww/kakoune/tree/cfbff4e132c8d0aed8bcaf677b25f5ab3a9c3221)), it seems auto-pairs have stopped working.
When inserting a `"([{'` the counterpart character is not inserted automatically.

**Comment by alexherbo2** [comment]
@CharlesGueunet All plugins have been updated and do not `require-module` or enable functionalities on their own.

It has been reflected in the [Installation] section.

[Installation]: https://github.com/alexherbo2/auto-pairs.kak#installation

See the discussion: https://github.com/alexherbo2/connect.kak/issues/29

**Comment by CharlesGueunet** [comment]
All right I just needed to update my conf to:

```
plug "alexherbo2/prelude.kak"
plug "alexherbo2/auto-pairs.kak" %{
  require-module prelude
  require-module auto-pairs
  auto-pairs-enable
}
```

Thanks for the help
