### ISSUE TITLE
Installation quesiton

### ISSUE THREAD

**Issue by m-kru** [alexherbo2/auto-pairs.kak#44]
In the installation section you mention about 2 options:
1. Add `auto-pairs.kak` to your autoload

or

2. source it manually.

Which one is done by `require-module auto-pairs`?

What does the opposite option look like?

**Comment by alexherbo2** [comment]
If you add auto-pairs.kak repository to your autoload, the files will be sourced by Kakoune at startup.  You can also use the `source` command to load the file manually.

The file defines a module that you have to require in your kakrc once sourced.

**Comment by m-kru** [comment]
That is a lot of step.
1. Place in autoload to be sourced,
2. `require-module` to do something (I do not know what as it already has been sourced),
3. `auto-pairs-enable`

Do you know why 1 and 2 are two distinct steps. At first glance it looks like they could be merged.

**Comment by alexherbo2** [comment]
Scripts define modules and nothing.

Source and require are separated to not introduce loading order issues, e.g. with plugins having dependencies.

When required, the module lets you acceed the commands, it does not install hooks, mappings, etc.  You use the enable commands, etc. for that.
