### ISSUE TITLE
Not matching pairs but only whitespaces

### ISSUE THREAD

**Issue by eko234** [alexherbo2/auto-pairs.kak#47]
I'm using your new implementation of autopairs but so far I can't seem to make it work, whenever i type any "pairable" character, it doesn't pair it but when i hit space it kinda matches the indentation downwards, I'm not sure if the last thing is intended, is there a way to disable it?, and why could it be that the plugin is not pairing my input?

Thanks.

**Comment by alexherbo2** [comment]
Do you have [kakoune.cr] and [jq] installed?

[kakoune.cr]: https://github.com/alexherbo2/kakoune.cr
[jq]: https://stedolan.github.io/jq/

And Kakoune with the [`write -method`][Discuss – kakoune.cr#20] support.

[Discuss – kakoune.cr#20]: https://discuss.kakoune.com/t/kakoune-cr/1605/20

**Comment by eko234** [comment]
I didn't had jq, installing it made it work, my version of kakoune doesnt have write -method support, but using it inside tmux seems to be enough to make it work, i think you should mention that jq is a dependency in the readme, thanks for your help and your cool plugins.

**Comment by basbebe** [comment]
I seem to have the same problem.
I do have kcr and jq installed and I do have `write -method` support

**Comment by basbebe** [comment]
`kak test.md`

```
sdf
```

press enter at end of word:

```
sdf
  

```

Now I have two spaces and an extra newline

https://github.com/basbebe/.dotfiles/blob/master/.config/kak/kakrc
