### ISSUE TITLE
Hitting <Backspace> in Insert mode deletes character after cursor

### ISSUE THREAD

**Issue by kkga** [alexherbo2/auto-pairs.kak#48]
- Kakoune is built from master (`v2020.09.01-400-gc507863a`)
- `kakoune.cr` is the latest nightly binary
- my current `kakrc`: https://github.com/kkga/dotfiles/blob/master/.config/kak/kakrc

I'm getting the following issue, as described in the title. Demonstrated in the video below.

I've tried playing with different options and disabling other plugins, but I still get this behavior. The only thing that helps is `auto-pairs-disable`.

Appreciate any tips on what could be wrong in my case.

P.S. I'm a new kak convert and just wanted to say thanks for all your plugins! My vimrc was 80% filled with plugins by tpope, and my kakrc is 80% filled with plugins by you :D

https://user-images.githubusercontent.com/1460122/112763484-49ad4980-900d-11eb-9348-ddcd5237d03b.mp4

**Comment by alexherbo2** [comment]
Hello,

You need the latest version of kakoune.cr and auto-pairs.kak with jq.  I recently made a breaking change, not sure that is related but could.

**Comment by kkga** [comment]
Latest `kcr` did fix this, thanks!
