### ISSUE TITLE
remove dependency on kakoune.cr

### ISSUE THREAD

**Issue by dead10ck** [alexherbo2/auto-pairs.kak#49]
It would be nice not to have this dependency, so that all that's needed for it to work is a `plug` command in your kakrc.

**Comment by alexherbo2** [comment]
Cannot until there is a good way for passing commands from the shell to Kakoune.

**Comment by dead10ck** [comment]
Sorry, I'm very new to Kakoune, but why is it necessary to shell out to begin with?

**Comment by alexherbo2** [comment]
It is used to generate the mappings from the auto-pairs option and determine when we are in pair to do the right action (`(▌)` → <kbd>Backspace</kbd> → `▌`).
