### ISSUE TITLE
Plug support?

### ISSUE THREAD

**Issue by gnull** [alexherbo2/auto-pairs.kak#52]
Are you planning to add support for installing this plugin with Plug?

The current way of putting things into `autoload` and installing dependencies by hand is cumbersome, and impossible to put in dotfiles. It would have been so great if users could just say `plug alexherbo2/auto-pairs.kak` and try out this project immediately.

This seems like a very useful project. I didn't try it yet (it's too late today already), but will soon!

**Comment by gnull** [comment]
Oh wait. Is it going to land in scripts that come with Kakoune itself?

**Comment by CBenoit** [comment]
You should be able to:
```
plug "alexherbo2/auto-pairs.kak" demand auto-pairs %{
    auto-pairs-enable
}
```

**Comment by gnull** [comment]
Ah, I didn't think about that!

But it didn't work from the first try. After adding the snippet you
provided and installing with `:plug-install`, Kakoune prints this at
startup:

```
*** This is the debug buffer, where debug info will be written ***
plug.kak: Error occured while loading 'alexherbo2/auto-pairs.kak' plugin:
          2:5: 'evaluate-commands' 6:1: 'evaluate-commands' no such command: 'auto-pairs'
```

**Comment by CBenoit** [comment]
Did you find how to get it working?
Was it by using `defer auto-pairs` instead of `demand auto-pairs`? I'm a bit surprised at the error you got, it's supposed to be sugar for `require-module auto-pairs`

**Comment by gnull** [comment]
Yes, I got the error message when I used `demand auto-pairs`.

I didn't do anything to install kakoune.cr; it's listed as a dependency in the README. Could it be the problem?

PS. Now I tried `defer auto-pairs` for completeness. It doesn't give me any errors, and the package isn't working: there's no command `auto-pairs-enable`.

**Comment by gnull** [comment]
Now I made it work. All I had to do was:

1. Add

   ```kak
   plug "alexherbo2/kakoune.cr" demand kakoune.cr
   
   plug "alexherbo2/auto-pairs.kak" demand auto-pairs %{
       auto-pairs-enable
   }
   ```
   to my kakrc.

2. Install kakoune.cr with `make install`.

Thank you for the help, @CBenoit.

**Comment by gnull** [comment]
But I think the issue is not resolved, because there's still no automatic way to install this package with dependencies and no instructions about it in the README.

Should I keep it open?

**Comment by gnull** [comment]
Wait, I get it. Plug doesn't normally handle the dependencies for the user, does it? Is the user supposed to do it manually?

**Comment by CBenoit** [comment]
Yeah exactly!
But you should change your config so it run `make install`automatically. Probably something like:
```
plug "alexherbo2/kakoune.cr" do %{
    make install
}
```
(as per [plug.kak documentation](https://github.com/andreyorst/plug.kak))

**Comment by gnull** [comment]
Thanks a lot!
