### ISSUE TITLE
Error: cannot unmap key that is currently executing

### ISSUE THREAD

**Issue by greenfork** [alexherbo2/auto-pairs.kak#60]
On the latest kakoune master this key sequence from the new line `(<enter>s` throws these errors

```
error running hook WinSetOption(inserted_pairs=0)/auto-pairs: 3:7: 'unmap': cannot unmap key that is currently executing
error running hook InsertChar(s)/auto-pairs: 2:7: 'unmap': cannot unmap key that is currently executing
```

I checked it with clear `kak -n` only sourcing this plugin.

Any workaround that comes to mind?

**Comment by greenfork** [comment]
Looks like this commit https://github.com/mawww/kakoune/commit/e49c0fb04095a2a1c546fd033ce2a1a6df3eb8d0 is responsible for this error. The version just before this commit works fine.

**Comment by krobelus** [comment]
typing the opening `(` adds this mapping

    map -docstring 'insert a new indented line in pair' window insert <ret> '<a-;>: insert-new-line-in-pair<ret>'

which unmaps itself. 
(`insert-new-line-in-pair` triggers a hook that unmaps `<ret>`).
We could allow the unmap to proceed. I don't see anything obviously wrong with the script.

**Comment by greenfork** [comment]
I suppose it will be fixed in the kakoune then. Just in case, still the same error on the latest master.

**Comment by krobelus** [comment]
this is fixed latest Kakoune master

**Comment by greenfork** [comment]
I can confirm, thanks!
