### ISSUE TITLE
Handle three quotes (for docstring in python)

### ISSUE THREAD

**Issue by maximbaz** [alexherbo2/auto-pairs.kak#8]
delimitMate is ~~very good at~~~ handling a special case of three quotes (used for docstrings in python), would be cool to have auto-pairs support it as wel:

![nvim-quotes](https://user-images.githubusercontent.com/1177900/43221308-cde705a6-904c-11e8-8bec-cc9bf364a046.gif)

**Comment by alexherbo2** [comment]
https://github.com/Raimondi/delimitMate

**Comment by alexherbo2** [comment]
@maximbaz What would have happened if you had inserted a fourth quote?

**Comment by maximbaz** [comment]
![quotes2](https://user-images.githubusercontent.com/1177900/44949489-e4802000-ae32-11e8-8902-38099cd99045.gif)

**Comment by alexherbo2** [comment]
Can you move over the quotes after inserting something?
