### ISSUE TITLE
Inserting newline places closing brace at wrong indentation level

### ISSUE THREAD

**Issue by andreyorst** [alexherbo2/auto-pairs.kak#9]
![pairs](https://user-images.githubusercontent.com/19470159/44658054-e3508c80-aa07-11e8-80b7-98266bfe8306.gif)
only `[]` and various quotes are expanding normally with newline.

**Comment by alexherbo2** [comment]
Auto-pairs doesn’t handle the indentation by itself, but triggers the normal hooks.

**Comment by andreyorst** [comment]
hm, indeed, I didn't noticed that before, because mainly inserted closing pair at right indentation already. Sorry for wrong issue report, but where should I dig then?

**Comment by alexherbo2** [comment]
Hm, maybe on [Kakoune] directly.

[Kakoune]: https://github.com/mawww/kakoune

**Comment by alexherbo2** [comment]
Which language is concerned?

**Comment by andreyorst** [comment]
> Which language is concerned?
c-family

**Comment by andreyorst** [comment]
So I've noticed that indentation actually works correctly, however the empty line is placed at wrong positon, and closing bracket too.
When auto-pairs are disabled, after I enter `{` and hit <kbd>Enter</kbd> the next line appears indented as it should:
![image](https://user-images.githubusercontent.com/19470159/48838814-8bbd8500-ed9a-11e8-985b-260df50a8eba.png)
(That thin gray line is a tab character)
With auto-pairs turned on, the indented line also exists, however the empty line is added before it, and closing paren is added on the indented line. That's the problem, and it's not issue with kakoune actually:
![image](https://user-images.githubusercontent.com/19470159/48838912-dccd7900-ed9a-11e8-853e-a9ecbd8e0019.png)

**Comment by maximbaz** [comment]
Does it repro with minimal kakrc and latest commit from this master? Doesn't seem to repro for me, also (finally working) unit tests are green and there are a couple of tests for a similar example.

**Comment by andreyorst** [comment]
yes. Fully empty kakrc, and manual sourcing auto-pairs still produces this issue for `c` filetype

**Comment by maximbaz** [comment]
What OS do you use?

Can you clone this repo and run unit tests, and tell me if any of them fail?

```
$ cd /path/to/auto-pairs
$ test/run /path/to/cloned/kakoune-repo/
```

**Comment by andreyorst** [comment]
I've re-cloned the repo, and issue is still here.
My os is Arch Linux, login shell is bash, user shell is zsh. sh is linked to dash.

tests log:
```
auto-pairs
    delete-closer
    delete-new-line
    delete-opener
    delete-opener-closer
    delete-single-quote
    delete-space
    insert-closer
    insert-nested-pairing
    insert-new-line
    insert-new-line-below
    insert-opener
    insert-opener-closer
    insert-single-quote
    insert-space
    surround-delete-opener
    surround-delete-space
    surround-insert-opener
    surround-insert-space

Resume: 18 tests, 0 failures
```

**Comment by andreyorst** [comment]
Here's me launching fresly compiled Kakoune from master branch, with `-n` and sourcing everything manually:
![problem](https://user-images.githubusercontent.com/19470159/48841579-e064fe00-eda2-11e8-9c72-3422882fb790.gif)

**Comment by maximbaz** [comment]
I wish I could help but I really have no clue how to investigate this if it doesn't repro via unit tests and on my machine with the same OS and shell as you 😞

**Comment by andreyorst** [comment]
this also happens for me in termux. I'll try to do fresh install of something like ubuntu in VB and try there to see if it is reproduces.

**Comment by andreyorst** [comment]
So. I did just downloaded Ubuntu 18.10 iso from official Ubuntu page.
Installed it in virtualbox.
Cloned kakoune and auto-pairs
Installed build-essential, libncurses-dev, and pkg-config or something like that.
Compiled kakoune, and done this:
![bug](https://user-images.githubusercontent.com/19470159/48981968-47f5b300-f0ed-11e8-9247-9df001a0c18a.gif)

**Comment by bugworm** [comment]
![screenshot_telegram_x_20181126-122409](https://user-images.githubusercontent.com/7214361/49008760-5ab4ca00-f177-11e8-99ff-bf89328cfbdb.png)
Kak in termux, rust lang

**Comment by maximbaz** [comment]
Managed to reproduce! So it happens only if you run `auto-pairs-enable` manually, and doesn't happen when it runs from WinCreate hook!

```
hook global WinCreate .* %{ auto-pairs-enable }
```

If I have this, it works fine. If I comment this and run `auto-pairs-enable` myself like on gifs above, the issue appears.

I have no clue as to _why_. @alexherbo2? But presumably `plug.kak` runs the command not from WinCreate hook and that's why you experience the issue?

**Comment by alexherbo2** [comment]
Maybe a race condition with the execution of hooks between the languages and auto-pairing.

**Comment by andreyorst** [comment]
@maximbaz personally I don't run this command in `plug` command, but you're right, **plug.kak** doesn't use hooks for commands it executes them with `execute-command` one by one, so this will still be reproducible with **plug.kak**.

Using your hook it works fine. But I tend to disable this automatic pair insertion time to time, as sometimes it just not what I want. In rare cases, but still.

**Comment by andreyorst** [comment]
Also using `auto-pairs-toggle` after successful `hook` breaks everything again.

**Comment by maximbaz** [comment]
Not sure if this can be solved in a meaningful way in the plugin itself. Was thinking about something like this to ensure auto-pairs' hooks are first:

- save current filetype
- set filetype to '' to 
- execute auto-pairs-enable
- restore filetype


But it feels hacky, also with `c` filetype it's just a lucky coincidence that `c` hooks don't misbehave after auto-pairs does its magic.

**Comment by dpc** [comment]
I cam here to report this exact issue. Can anyone describe in more detail what is the problem?

**Comment by andreyorst** [comment]
> Can anyone describe in more detail what is the problem?

Seems like if plugin defines it's hooks before filetype hooks the order for executing hooks is correct. Solution for now is to activate plugin by such hook: `hook global WinCreate .* %{ auto-pairs-enable }`

> It’s a problem that should be addressed upstream.

Well I guess then you should adress it upstream as a maintainer? I'm not sure how to do it properly since I don't know deep enough how your plugin is working, and what's actually causing an issue here.

**Comment by alexherbo2** [comment]
Even without auto-pairs, the indentation is wrong.

**Comment by andreyorst** [comment]
I know that there are problems with lisp filetype indentation (it adds extra space on every line for some reason), but for c-family I was pretty much pleased with indentation handling most of the time.

**Comment by alexherbo2** [comment]
I can add a fix, but there is two bugs that should be corrected in C-family before.

**Comment by dgrisham** [comment]
I assume this is still waiting on https://github.com/mawww/kakoune/issues/2590?

**Comment by andreyorst** [comment]
I don't think that this issue is related

**Comment by alexherbo2** [comment]
https://github.com/mawww/kakoune/issues/2806

**Comment by alexherbo2** [comment]
@andreyorst 6abc67f Does it help?

**Comment by andreyorst** [comment]
it looses indentation. Cursor is placed correctly though.

With this hook `hook global WinCreate .* %{ auto-pairs-enable }`:

```c
int main() {|}
RET
int main() {
    |
}
```

after 2 `auto-pairs-toggle`:

```
int main() {|}
RET
int main() {
|
}
```

**Comment by alexherbo2** [comment]
I don’t know how to solve the hook execution order.

**Comment by andreyorst** [comment]
Actually, because of this long standing issue I've stopped using auto pairs in all editors :D

**But** your solution for surrounding is outstanding and I use this plugin for it every day.

**Comment by alexherbo2** [comment]
Wow thanks
